version: "3.9"
services:
  # frontend:
  #   build: ./html
  #   image: webApp:latest
  #   ports:
  #     - 8085:80
  #   container_name: webApp
  backend:
    # build: ./
    image: jeffbla/expressjs:latest
    ports:
      - 8080:8080
    container_name: expressjs
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: rentweb
    volumes:
      - pgdata:/var/lib/postgresql/data/

volumes:
  pgdata:
